### PR TITLE
Fix rendering after Vecty API changes.

### PR DESCRIPTION
**Pull request by shurcooL**
The goal of this PR is to make the smallest needed change to have correct rendering behavior, that's it. It should be as small as possible. It's a subset of #86.

See individual commit messages for more details.

### CODE REVIEW

**Comment by shurcooL** [comment]
Unfortunately, this change doesn't seem to be enough to have correct rendering. I'm still seeing a bug, but it's different than before. It's reproducible using the usual `mock.html` page.

How it should look like after last render:

image

image

How it actually looks:

image

image

Note that the "changes-list" class is missing. It happens only after the final render, when all elements are shifted by one because the "checking for updates..." heading goes away.

Any ideas what's causing the incorrect rendering behavior @pdf or @slimsag?

**Comment by pdf** [comment]
Not off the top of my head, no.  It's really hard to do any debugging without source maps though.

**Comment by shurcooL** [comment]
Thanks.

I'll try to investigate more and see how hard it is to make a smaller repro. The changes you did in #86 didn't have this issue. But I'm interested in finding out what's causing it, in case it's a bug in rendering which would be worth fixing rather than working around.

**Comment by pdf** [comment]
It must be a bug, so I would certainly like to fix it.  In #86, that element would never get replaced, just moved which I suspect is why it wasn't evident there.  I'll also try to find a repro, but probably not until the weekend.

**Comment by pdf** [comment]
Had a little time this evening to test and was able to reproduce the problem easily enough.  Will be fixed by merging gopherjs/vecty#154 linked above.  The bug is triggered by replacing an element with a new element of a different type, when both elements share properties with matching keys and values.

**Comment by slimsag** [comment]
Major thanks pdf for investigating / fixing this so quickly! I've just merged his PR https://github.com/gopherjs/vecty/pull/154 above, so I think this should be fixed now :)

**Comment by shurcooL** [comment]
It is indeed. I'm not seeing any other issues, so I can proceed with merging this PR now. Thank you again @pdf and @slimsag!

**Pull request merged**
